name: Unit Tests # name of the test

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Unit Test sum
        run: npm test ./__tests__/sum.test.js
      - name: Unit Test unit
        run: npm test ./__tests__/unit.test.js
